---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: my-namespace
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    app: dov
    env: test
  ports:
  - name: svc-web-port
    port: 5000
    targetPort: web-port
  - name: svc-metric-port
    port: 5100
    targetPort: metric-port