---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bgg-config-map
  namespace: bggns-1
data:
  BGG_DB_USER: root
  BGG_DB_HOST: bggdb-svc.bggns-1.svc.cluster.local
---
apiVersion: v1
kind: Secret
metadata:
  name: bgg-secret
  namespace: bggns-1
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=