---
apiVersion: v1
kind: Namespace
metadata:
  name: bggns-1

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-deploy-db
  namespace: bggns-1
  labels:
    name: bgg-deploy-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bgg-db
      env: test
  template:
    metadata:
      name: bgg-db
      namespace: bggns-1
      labels:
        app: bgg-db
        env: test
    spec:
      containers:
      - name: bgg-db-container
        image: stackupiss/bgg-database:v1
        imagePullPolicy: IfNotPresent
        ports:
        - name: db-port
          containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: bggdb-svc
  namespace: bggns-1
  labels:
    app: bggdb
    name: bggdb-svc
spec:
  type: ClusterIP
  selector:
    app: bgg-db
    env: test
  ports:
  - name: svc-db-port
    port: 3306
    targetPort: db-port