---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgg-deploy-app
  namespace: bggns-1
  labels:
    name: bgg-deploy-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg-app
      env: test
  template:
    metadata:
      name: bgg-app
      namespace: bggns-1
      labels:
        app: bgg-app
        env: test
    spec:
      containers:
      - name: bgg-app-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        env:
        - name: BGG_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: bgg-secret
              key: BGG_DB_PASSWORD
        envFrom:
        - configMapRef:
            name: bgg-config-map
        ports:
        - name: app-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: app-port
          periodSeconds: 30
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns-1
  labels:
    app: bggapp
    name: bggapp-svc
spec:
  type: ClusterIP
  # type: NodePort
  # type: LoadBalancer
  selector:
    app: bgg-app
    env: test
  ports:
  - name: svc-app-port
    port: 5000
    targetPort: app-port