---
apiVersion: v1
kind: ConfigMap
metadata:
  name: code-server-config-map
  namespace: tammy-code-server
data:
  TZ: Asia/Singapore
  DEFAULT_WORKSPACE: /config/workspace
  PROXY_DOMAIN: code-163.47.11.104.nip.io
---
apiVersion: v1
kind: Secret
metadata:
  name: code-server-secret
  namespace: tammy-code-server
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=