---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dov-cm
  namespace: my-namespace
data:
  INSTANCE_NAME: name from configmap
---
apiVersion: v1
kind: Secret
metadata:
  name: dov-secret
  namespace: my-namespace
type: Opaque
data:
  INSTANCE_NAME: dGVzdA==
---