apiVersion: apps/v1
kind: Deployment
metadata:
  name: dov-deploy
  namespace: my-namespace
  labels:
    name: dov-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dov
      env: test
  template:
    metadata:
      name: dov-po
      namespace: my-namespace
      labels:
        app: dov
        env: test
    spec:
      containers:
      - name: dov-container
        image: tammyisaninja/dov-bear:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: INSTANCE_HASH
          valueFrom:
            fieldRef:
              # fieldPath: metadata.labels['app']
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: dov-cm
        ports:
        - name: web-port
          containerPort: 3000
        - name: metrics-port
          containerPort: 3100
        livenessProbe:
          httpGet:
            path: /healthz
            port: web-port
          periodSeconds: 30
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: dov-svc
  namespace: my-namespace
  labels:
    app: dov
    name: dov-svc
spec:
  type: ClusterIP
  selector:
    app: dov
    env: test
  ports:
  - name: svc-web-port
    port: 5000
    targetPort: web-port
  - name: svc-metric-port
    port: 5100
    targetPort: metric-port